### ISSUE TITLE
Cannot download files.

### ISSUE THREAD

**Issue by yaccovs** [bjesus/asam#4]
<pre>Started GET "/system/photos/1/original/test.pdf?1360765905" for 127.0.0.1 at Wed Feb 13 16:32:23 +0200 2013

ActionController::RoutingError (No route matches [GET] "/system/photos/1/original/test.pdf"):
  

Rendered /var/lib/gems/1.8/gems/actionpack-3.1.10/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (0.5ms)
</pre>

**Comment by bjesus** [comment]
umm.. few pointers to check:
- what's your RAILS_ENV ? are you maybe running on "production"? you can check Rails.env on the console.
- was the upload successful? can you check if the file is actually there? (./public/system/photos/1/original/test.pdf) is there a folder named /public/system at all?
- does everything else looks fine? are JSs/CSSs loaded, or is everything until ./public not accessible? i.e. can you reach /javascripts/modernizr-1.6.min.js ?

thank you for reporting this!

**Comment by yaccovs** [comment]
Answers:
1. RAILS_ENV=test
2. this folder doesnt exist. but i see the file in the folder photos, located out of the public. after <pre>mkdir public/system;
cd public/system;
ln -s ../../photos</pre> the problem (kind of) solved.

Thank you about the development of the project

**Comment by bjesus** [comment]
hey glad it fixed it for you. i'll add that folder to the repo.
what do you mean "kind of"? are there still problems?

sorry it took me a while to respond, was abroad for a few days.

**Comment by yaccovs** [comment]
Original folder still wrong location.

**Comment by bjesus** [comment]
i can't really understand what was the symlink for?

**Comment by yaccovs** [comment]
```
[paperclip] Saving attachments.
[paperclip] saving photos/1/original/test.pdf
[paperclip] saving photos/1/thumb/test.JPG
```

Not in the "public/system/photos".
So I created a symlink from public/system/photos to photos/

**Comment by bjesus** [comment]
okay, found the issue with the wrong directory. no need for symlink anymore. thanks for reporting
